name: Deploy react-hooks-and-components to GitHub Pages

on:
  push:
    branches: [ react-hooks-and-components ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: home-work-40

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to folder inside gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: home-work-40/dist
          destination_dir: home-work-40
